In [5]:
# importing numpy
import numpy as np

# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
a = np.array([1,2,3,5,0])
print(a)
print("non zero?", np.all(a))

[1 2 3 5 0]
non zero? False


In [6]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
a2 = np.array([3, -1, 3, 7, 2])
print(a2)
print("non-zero?", np.any(a2))

[ 3 -1  3  7  2]
non-zero? True


In [7]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
a3 = np.array([0,0,0,0])
print(a3)
print("non zero?", np.any(a3))

[0 0 0 0]
non zero? False


In [8]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
a4 = np.array([56, -2, 7])
print(a4)
print("Memory bytes):", a4.nbytes)

[56 -2  7]
Memory bytes): 24


In [9]:
# Create a numpy array with 10 zeros and print the array.
zeros = np.zeros(10)
print(zeros)

# Create a numpy array with 6 ones and print the array.
ones = np.ones(6)
print(ones)

# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
threes = np.full(12, 3)
print(threes)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3 3 3 3 3 3 3 3 3 3 3 3]


In [10]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
number = np.arange(8, 21)
print(number)

# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
even_number = np.arange(8, 21, 2)
print(even_number)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [11]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
r = np.random.normal(2, 0.5, 100)

print("Mean:", np.mean(r))
print("Max:", np.max(r))
print("Min:", np.min(r))
print("Std:", np.std(r))

# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
r1 = np.random.normal(2, 0.5, 1000)

print("Mean:", np.mean(r1))
print("Max:", np.max(r1))
print("Min:", np.min(r1))
print("Std:", np.std(r1))
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
r2 = np.random.normal(2, 0.5, 1000000)

print("Mean:", np.mean(r2))
print("Max:", np.max(r2))
print("Min:", np.min(r2))
print("Std:", np.std(r2))
# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?


Mean: 2.047175089553808
Max: 3.154958557739131
Min: 0.6901641151721454
Std: 0.5179881645759071
Mean: 2.0238692424706546
Max: 3.4275686593090846
Min: 0.6373343346565468
Std: 0.48760659082811986
Mean: 2.0004974294210225
Max: 4.367262806862531
Min: -0.5459414457303651
Std: 0.5004468661139291
