<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [2]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [ ]:
arrB =np.array([[5,2,3],[6,1,3],[2,4,1]])
print(arrA)

[[5 2 3]
 [6 1 3]
 [2 4 1]]


In [5]:
arrB = arrA[:2,:2]
print(arrB)

[[5 2]
 [6 1]]


In [9]:
arrC = arrA[1:,1:]
print(arrC)

[[1 3]
 [4 1]]


In [11]:
arrD = np.array([[4,-7,4],[5,6,-1],[-4,2,5]])
arrAD = np.matmul(arrA,arrD)
print(arrAD)
arrDA = np.matmul(arrD,arrA)
print(arrDA)
print("AD is not equal to DA")

[[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]
[[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]
AD is not equal to DA


In [16]:
detB = (5*1) - (2*6)
print("Determinant of B calculated manually:", detB)
print("Determinant of B using numpy:", det(arrB))

invB = (1/detB) * np.array([[1,-2],[-6,5]])
print("Inverse of B calculated manually:\n", invB)
print("Inverse of B using numpy:\n", inv(arrB))
print("Verification (B * B_inv):\n", np.matmul(arrB, invB))

Determinant of B calculated manually: -7
Determinant of B using numpy: -6.999999999999999
Inverse of B calculated manually:
 [[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]
Inverse of B using numpy:
 [[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]
Verification (B * B_inv):
 [[1. 0.]
 [0. 1.]]


In [21]:
#making arrD all integers to remove uncclear floats
intarrD = arrD.astype(int)
invD = inv(intarrD)
print("Inverse of D using numpy:\n", invD)
print("Verification (D * D_inv):\n", np.matmul(arrD, invD))
print("Verification (D_inv * D):\n", np.matmul(invD, arrD))


Inverse of D using numpy:
 [[ 0.07785888  0.10462287 -0.04136253]
 [-0.05109489  0.08759124  0.05839416]
 [ 0.08272506  0.0486618   0.14355231]]
Verification (D * D_inv):
 [[ 1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 6.93889390e-17  1.00000000e+00 -5.55111512e-17]
 [-1.38777878e-17 -8.32667268e-17  1.00000000e+00]]
Verification (D_inv * D):
 [[ 1.00000000e+00  6.93889390e-17  6.93889390e-18]
 [ 2.77555756e-17  1.00000000e+00 -2.08166817e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
